body:
  - type: textarea
    attributes:
      label: New Seasonal Theme!
      value: |
        We are looking some cool seasonal theme design(s) for our brand! We'll make a vote on 8 July and the designs will stay during 9 July-25 August, 2023.
        
        - If you have any idea,
        - If you are interested or have any design,
        please share it in this discussion!
        
        Do not forget, we'll add your name to our contributor list if you help us to make a design!
    validations:
      required: true