body:
  - type: markdown
    attributes:
      value: "https://www.un.org/en/observances/list-days-weeks"
  - type: textarea
    attributes:
      label: Upcoming Dates
      value: |
        - **:** 
        - **:** 

        We would be happy if someone help us to make design(s) for these days!
    validations:
      required: true
#  - type: textarea
#    attributes:
#      label: Announcement
#      value: "We would be happy if someone help us to make design(s) for these days!"
#    validations:
#      required: true